---
- hosts: all
  tasks:
    - name: test connection
      ping:
    - name: install the latest version of selinux package
      yum:
        name: 
          - policycoreutils
          - policycoreutils-python
          - setools
          - setools-console
          - setroubleshoot
        state: latest
        become_user: root
#   - name: Put SELinux in permissive mode, logging actions that would be blocked.
#       selinux:
#       policy: targeted
#       state: permissive
