---
- hosts: all
  tasks:
    - name: test connection
      ping:
    - name: install the latest version of selinux package
      yum:
        name: 
          - policycoreutils
          - setools
          - setools-console
          - setroubleshoot
        state: latest
      become: true
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive
      become: true
