---
- hosts: all
  tasks:
    - name: test connection
      ping:  
    - name: return ip address of remote host(s)
      debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
    - name: install the latest version of selinux package
      yum:
        name: 
          - policycoreutils
          - setools
          - setools-console
          - setroubleshoot
        state: latest
      become: True
#    - name: Put SELinux in permissive mode, logging actions that would be blocked.
#      selinux:
#        policy: targeted
#        state: permissive
#      become: True
