---
- hosts: all
  tasks:
    - name: test connection
      ping:
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive
